Reset the make_dist_tarball script
Apparently contained some weird mojo that we still
require - will take a bit more effort to unravel.

Signed-off-by: Ralph Castain <rhc@pmix.org>

diff --git a/contrib/dist/make_dist_tarball b/contrib/dist/make_dist_tarball
--- a/contrib/dist/make_dist_tarball
+++ b/contrib/dist/make_dist_tarball
@@ -10,11 +10,9 @@
 #                         University of Stuttgart.  All rights reserved.
 # Copyright (c) 2004-2005 The Regents of the University of California.
 #                         All rights reserved.
-# Copyright (c) 2008-2018 Cisco Systems, Inc.  All rights reserved
-# Copyright (c) 2015-2019 Intel, Inc.  All rights reserved.
-# Copyright (c) 2019      Amazon.com, Inc. or its affiliates.  All Rights
-#                         reserved.
-# Copyright (c) 2024      Nanook Consulting  All rights reserved.
+# Copyright (c) 2008-2020 Cisco Systems, Inc.  All rights reserved
+# Copyright (c) 2016-2020 Intel, Inc.  All rights reserved.
+# Copyright (c) 2021-2024 Nanook Consulting  All rights reserved.
 # $COPYRIGHT$
 #
 # Additional copyrights may follow
@@ -30,6 +28,7 @@ M4_TARGET_VERSION=1.4.17
 AM_TARGET_VERSION=1.15
 AC_TARGET_VERSION=2.69
 LT_TARGET_VERSION=2.4.6
+FLEX_TARGET_VERSION=2.5.35
 
 #
 # When running "make distcheck", use these parallelization flags.  Can
@@ -48,87 +47,57 @@ DISTCHECK_MAKE_FLAGS=-j4
 # Default to requiring *exact* versions if we're making distribution
 # tarballs; but higher-than-expected versions are ok for
 # non-distribution tarballs.
+autogen_args=
+distdir=".."
+greekonly=0
+nogreek=0
 dirty_ok=0
 gnu_version_ignore=0
-mac=0
 dist_target=distcheck
 distcheck_flags="AM_MAKEFLAGS=$DISTCHECK_MAKE_FLAGS"
+git_update=1
+
 if test "`basename $0`" = "make_tarball"; then
     dist_target=dist
-    distcheck_flags=
+    distcheck_flags="AM_MAKEFLAGS=-j32"
     highok=1
     dirty_ok=1
+    greekonly=1
 else
     highok=0
 fi
 
-greekonly=0
-autogen_args=
-config_args=
-distdir=".."
-for i in "$@"; do
-    case $i in
-        -greekonly) greekonly=1 ;;
+while test "$1" != ""; do
+    case $1 in
         --greekonly) greekonly=1 ;;
-        -highok) highok=1 ;;
+        --no-greek) nogreek=1 ;;
         --highok) highok=1 ;;
-        -autogen-args=*) autogen_args="${i#*=}"; shift ;;
-        --autogen-args=*) autogen_args="${i#*=}"; shift ;;
-        -config-args=*) config_args="${i#*=}"; shift ;;
+        --autogen-args) autogen_args=$2; shift ;;
         --config-args=*) config_args="${i#*=}"; shift ;;
-        -distdir=*) distdir="${i#*=}"; shift ;;
-        --distdir=*) distdir="${i#*=}"; shift ;;
+        --distdir) distdir=$2; shift ;;
         --dirtyok) dirty_ok=1 ;;
-        --verok) gnu_version_ignore=1 ;;
-        -verok) gnu_version_ignore=1 ;;
-        --macosx) mac=1 ;;
-        -macosx) mac=1 ;;
+        --verok) gnu_version_ignore=1;;
+        --no-git-update) git_update=0;;
         *)
             cat <<EOF
 Unrecognized argument: $1
 
 Valid arguments:
   --greekonly     Only build the greek tarball (vs. both tarballs)
+  --no-greek      Do not build the greek tarball
   --highok        Ok if Autotools versions are too high
   --autogen-args  Arguments to pass to autogen
-  --config-args   Arguments to pass to configure (e.g., --with-libevent=<foo>)
+  --config-args  Arguments to pass to configure
   --distdir       Move the tarball(s) to this directory when done
   --dirtyok       Ok if the source tree is dirty
   --verok         Ignore result of autotools version checking
-  --macosx        Allow execution on Mac OSX
+  --no-git-update Skip "git pull" part, assume local repo is updated already
 EOF
             exit 1
             ;;
     esac
     shift
 done
-
-# check for OS type - we do not allow building tarballs on
-# MacOSX by default as it can create problems when unpacking
-# the tarball on Linux. See
-# for details.
-if [[ $mac != 1 ]]; then
-    if [[ "$OSTYPE" == "darwin"* ]]; then
-        echo "\n*** Building a tarball on MacOSX results in a"
-        echo "*** tarball that includes undesirable artifacts"
-        echo "*** when unpacked on Linux systems. We therefore"
-        echo "*** do not support this operation by default.\n"
-        echo "*** If you do need to execute this on MacOSX, then"
-        echo "*** you can override this warning by setting the"
-        echo "*** --macosx option on the cmd line\n"
-        exit 1
-    fi
-fi
-
-# PRRTE needs libevent to build.  If $LIBEVENT is set in the
-# environment, automatically add it to the config_args.
-if test "$LIBEVENT" != ""; then
-    echo "*** Found \$LIBEVENT: $LIBEVENT"
-    echo "*** Adding --with-libevent=$LIBEVENT to config_args"
-    config_args="--with-libevent=$LIBEVENT $config_args"
-fi
-
-export DISTCHECK_CONFIGURE_FLAGS=$config_args
 
 #
 # First things first -- check that the auto versions that we have are
@@ -201,6 +170,7 @@ m4: $M4_TARGET_VERSION
 Automake: $AM_TARGET_VERSION
 Autoconf: $AC_TARGET_VERSION
 Libtool:  $LT_TARGET_VERSION
+Flex:     $FLEX_TARGET_VERSION
 
 Either change this script to match the found version, or install
 the correct version of the tools.
@@ -223,6 +193,7 @@ m4: $M4_TARGET_VERSION
 Automake: $AM_TARGET_VERSION
 Autoconf: $AC_TARGET_VERSION
 Libtool:  $LT_TARGET_VERSION
+Flex:     $FLEX_TARGET_VERSION
 
 Either change this script to match the found version, or install
 the correct version of the tools.
@@ -243,9 +214,13 @@ m4: $M4_TARGET_VERSION
 Automake: $AM_TARGET_VERSION
 Autoconf: $AC_TARGET_VERSION
 Libtool:  $LT_TARGET_VERSION
+Flex:     $FLEX_TARGET_VERSION
 
+This is *usually* ok, but this script is going to sleep for 5 seconds
+to give you the chance to quit before doing anything.
 ----------------------------------------------------------------------
 EOF
+            sleep 5
         fi
 
     elif test "$result" = "unknown"; then
@@ -260,6 +235,7 @@ m4: $M4_TARGET_VERSION
 Automake: $AM_TARGET_VERSION
 Autoconf: $AC_TARGET_VERSION
 Libtool:  $LT_TARGET_VERSION
+Flex:     $FLEX_TARGET_VERSION
 
 Either change this script to match the found version, or install
 the correct version of the tools.
@@ -282,7 +258,7 @@ make_tarball() {
     #
     echo "*** Running autogen $autogen_args..."
     rm -f success
-    (./autogen.pl $autogen_args 2>&1 && touch success) | tee auto.out
+    (./autogen.pl --force $autogen_args 2>&1 && touch success) | tee auto.out
     if test ! -f success; then
         echo "Autogen failed.  Aborting"
         exit 1
@@ -300,6 +276,14 @@ make_tarball() {
     fi
 
     #
+    # Remove all generated *_lex.c files so that we ensure to invoke
+    # flex from here in this script (to ensure that we're using a good
+    # version of flex, and not picking up random *_lex.c files that
+    # happened to be in the tree already).
+    #
+    echo "*** Removing old generated flex files..."
+    find . -name \*_lex.c -exec chmod ug+rw {} \; -exec rm -f {} \; -print
+
     #
     # make tarball
     #
@@ -307,7 +291,7 @@ make_tarball() {
     save_LD=$LD_LIBRARY_PATH
     LD_LIBRARY_PATH=
     rm -f success
-    (eval make $distcheck_flags $dist_target 2>&1 && touch success) | tee dist.out
+    (make $distcheck_flags $dist_target 2>&1 && touch success) | tee dist.out
     if test ! -f success; then
         echo "Make $dist_target failed.  Aborting"
         exit 1
@@ -332,29 +316,69 @@ start=`date`
 echo "*** Start time: $start"
 
 echo "*** Checking tools versions..."
-check_gnu_version m4 $M4_TARGET_VERSION
-check_gnu_version automake $AM_TARGET_VERSION
-check_gnu_version autoconf $AC_TARGET_VERSION
-if test $mac -eq 0; then
+if test "$gnu_version_ignore" = "0"; then
+    check_gnu_version m4 $M4_TARGET_VERSION
+    check_gnu_version automake $AM_TARGET_VERSION
+    check_gnu_version autoconf $AC_TARGET_VERSION
     check_gnu_version libtool $LT_TARGET_VERSION
+    # Windows needs a recent version of flex; old versions don't generate
+    # Windows-friendly *_lex.c files.
+    check_gnu_version flex $FLEX_TARGET_VERSION
 fi
+
 #
-# Verify that we're in a top PRRTE dir
+# Verify that we're in a top PRTE dir
 #
-echo "*** Checking to ensure in top-level PRRTE directory..."
-if test -f VERSION -a -f configure.ac -a -f config/prte_mca.m4 ; then
+echo "*** Checking to ensure in top-level PMIx Reference RunTime Environment directory..."
+if test -f VERSION -a -f configure.ac -a -f config/prte_get_version.m4 ; then
     happy=1
 else
-    echo "Do not appear to be in an PRRTE top directory.  Abort!"
+    echo "Do not appear to be in an PMIx Reference RunTime Environment top directory.  Abort!"
     exit 1
 fi
 
+if test $git_update -eq 1; then
+
+    #
+    # Get the latest
+    #
+    echo "*** Git pull to get the latest..."
+    git pull --rebase
+    if test $? -ne 0; then
+        echo "*** Git pull failed.  Cannot continue."
+        exit 1
+    fi
+fi
+
+#
+# Ensure we have a clean repo
+#
+if test $dirty_ok -eq 0; then
+    echo "*** Checking if source tree is dirty..."
+    dirty=0
+    file=git-status.$$.out
+    git status > $file
+    if test "`grep 'Changes not staged for commit' $file`" != "" ||
+       test "`grep 'Changes staged for commit' $file`" != ""; then
+        dirty=1
+    fi
+    rm -f $file
+
+    if test $dirty -eq 1; then
+        echo "    Source tree is dirty.  Cannot continue."
+        exit 1
+    fi
+fi
+
+#
+# Get our repo_rev
+#
 echo "*** Removing old VERSION file..."
 rm -f VERSION
 echo "*** Restoring pristine VERSION file..."
-git checkout HEAD -- VERSION
-echo "*** Getting git version number..."
-repo_rev=git`git log -1 --oneline | head -1 | cut -d' ' -f1`
+git checkout VERSION
+echo "*** Getting git version..."
+repo_rev=`git describe --tags --always`
 echo "    Repo rev number: $repo_rev"
 
 # Sanity checks
@@ -366,32 +390,18 @@ elif test "`echo $repo_rev | grep ' '`" != ""; then
     exit 1
 fi
 
-# Ensure we have a clean repo
-if test $dirty_ok -eq 0; then
-    echo "*** Checking if source tree is dirty..."
-    dirty=0
-    if test "`git status | grep 'Changes not staged for commit'`" != ""; then
-        dirty=1
-    fi
-
-    if test $dirty -eq 1; then
-        echo "    Source tree is dirty.  Cannot continue."
-        exit 1
-    fi
-fi
-
 #
-# Ditch repo rev from all version numbers
+# Set final values in VERSION
 #
-echo "*** Removing git version numbers from VERSION..."
+echo "*** Removing version numbers from VERSION..."
 version_files=VERSION
 release_date=`date '+%b %d, %Y'`
 echo "    Release date: $release_date"
 for file in $version_files; do
     echo " - $file"
-    sed -e 's/^want_repo_rev=.*/want_repo_rev=0/' \
-        -e 's/^repo_rev=.*/'repo_rev=$repo_rev/ \
+    sed -e 's/^repo_rev=.*/'repo_rev=$repo_rev/ \
         -e "s/^date=.*/date=\"$release_date\"/" \
+        -e "s/^tarball_version=.*/tarball_version=/" \
         $file > $file.new
     cp -f $file.new $file
     rm $file.new
@@ -406,21 +416,23 @@ done
 # unless the user specifically said --greekonly, then only make the
 # greek tarball.  Making both tarballs at once allows us to guarantee
 # to have two tarballs -- one greek and one not -- that have exactly
-# the same GIT r number (as opposed to, for example, running this
+# the same SVN r number (as opposed to, for example, running this
 # script to make a greek tarball, then running it again to make a
 # non-greek tarball -- there is a race condition that someone could
-# commit in the meantime and change the GIT r number in the 2nd
+# commit in the meantime and change the SVN r number in the 2nd
 # tarball)
 #
 
-# First, make greek tarball
+# First, if ! --no-greek, make greek tarball
 
-echo "*** Making greek tarball"
-make_tarball
+if test $nogreek -eq 0; then
+    echo "*** Making greek tarball"
+    make_tarball
+fi
 
 # Now if ! --greekonly, make the non-greek tarball
 
-if test "$greekonly" = "0"; then
+if test $greekonly -eq 0; then
     echo "*** REMOVING ALL GREEK FROM VERSION NUMBERS!!"
     for file in $version_files; do
         echo " - $file"
@@ -433,7 +445,8 @@ if test "$greekonly" = "0"; then
 fi
 
 # Put the VERSION file back the way it was
-git checkout HEAD -- VERSION
+rm -f VERSION
+git checkout VERSION
 
 echo " "
 echo "*** Start time:  $start"
